# Generated by Django 4.2.30 on 2026-07-08 22:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('HOTEL', 'Hotel'), ('GUESTHOUSE', 'Guesthouse / B&B'), ('SHORT_STAY', 'Short-Stay Apartment'), ('LONG_TERM', 'Long-Term Rental')], db_index=True, max_length=20)),
                ('region', models.CharField(choices=[('GREATER_ACCRA', 'Greater Accra'), ('ASHANTI', 'Ashanti'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('WESTERN', 'Western'), ('VOLTA', 'Volta'), ('NORTHERN', 'Northern'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('BONO', 'Bono'), ('BONO_EAST', 'Bono East'), ('AHAFO', 'Ahafo'), ('SAVANNAH', 'Savannah'), ('NORTH_EAST', 'North East'), ('OTI', 'Oti'), ('WESTERN_NORTH', 'Western North')], db_index=True, max_length=20)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('amenities', models.JSONField(default=list)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('total_beds', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_VERIFICATION', 'Pending Verification'), ('LIVE', 'Live on Platform'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='DRAFT', max_length=25)),
                ('rejection_reason', models.TextField(blank=True)),
                ('rating_average', models.FloatField(default=0.0)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('SUITE', 'Suite'), ('APARTMENT', 'Apartment'), ('STUDIO', 'Studio'), ('ENTIRE_HOUSE', 'Entire House/Villa')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('beds_single', models.PositiveIntegerField(default=0)),
                ('beds_double', models.PositiveIntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_available', models.BooleanField(default=True)),
                ('total_units', models.PositiveIntegerField(default=1)),
                ('has_ac', models.BooleanField(default=False)),
                ('has_tv', models.BooleanField(default=False)),
                ('has_private_bathroom', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='properties.property')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['property', 'price_per_night'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_guest', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='properties.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
