# Generated by Django 4.2.30 on 2026-07-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_units',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms currently available for booking'),
        ),
    ]
