# Generated by Django 4.2.30 on 2026-07-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_room_available_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='units_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
