# Generated by Django 4.2.30 on 2026-07-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted by Agent'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='ASSIGNED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes from admin to agent')),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_assignments', to=settings.AUTH_USER_MODEL)),
                ('assigned_by', models.ForeignKey(limit_choices_to={'is_staff': True, 'user_type': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='properties.property')),
            ],
            options={
                'verbose_name': 'Verification Assignment',
                'verbose_name_plural': 'Verification Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verdict', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CLARIFICATION', 'Needs Clarification')], max_length=25)),
                ('agent_notes', models.TextField()),
                ('property_exists', models.BooleanField(default=True)),
                ('property_matches_description', models.BooleanField(default=True)),
                ('photos_are_accurate', models.BooleanField(default=True)),
                ('location_is_correct', models.BooleanField(default=True)),
                ('amenities_verified', models.JSONField(default=dict, help_text='Which amenities were confirmed on-site')),
                ('evidence_photos', models.JSONField(default=list, help_text='List of photo URLs taken during inspection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='verification.verificationassignment')),
            ],
            options={
                'verbose_name': 'Verification Report',
                'verbose_name_plural': 'Verification Reports',
            },
        ),
    ]
