# Generated by Django 4.2.30 on 2026-07-08 19:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_picture', models.URLField(blank=True, help_text='URL to profile picture (stored in cloud storage later)', max_length=500, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('GUEST', 'Guest / Traveler'), ('HOST', 'Property Host / Landlord'), ('AGENT', 'Verification Agent'), ('ADMIN', 'Platform Administrator')], db_index=True, default='GUEST', max_length=10)),
                ('verification_level', models.CharField(choices=[('NONE', 'Not Verified'), ('BASIC', 'Phone Verified'), ('ID_VERIFIED', 'Government ID Verified'), ('FULL', 'Full Background Check Complete')], default='NONE', max_length=20)),
                ('phone_verified', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('government_id_verified', models.BooleanField(default=False)),
                ('government_id_type', models.CharField(blank=True, max_length=50, null=True)),
                ('government_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('government_id_document', models.URLField(blank=True, help_text='URL to ID document (stored in cloud storage later)', max_length=500, null=True)),
                ('trust_score', models.IntegerField(default=0, help_text='0-100 reliability score')),
                ('completed_bookings', models.IntegerField(default=0)),
                ('cancelled_bookings', models.IntegerField(default=0)),
                ('host_rating_average', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['user_type', 'verification_level'], name='users_user_user_ty_dfa99e_idx'), models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx')],
            },
        ),
    ]
