# Generated by Django 4.2.30 on 2026-07-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_verifications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether a verification agent is available for new assignments'),
        ),
        migrations.AddField(
            model_name='user',
            name='region_of_operation',
            field=models.CharField(blank=True, choices=[('GREATER_ACCRA', 'Greater Accra'), ('ASHANTI', 'Ashanti'), ('CENTRAL', 'Central'), ('EASTERN', 'Eastern'), ('WESTERN', 'Western'), ('VOLTA', 'Volta'), ('NORTHERN', 'Northern'), ('UPPER_EAST', 'Upper East'), ('UPPER_WEST', 'Upper West'), ('BONO', 'Bono'), ('BONO_EAST', 'Bono East'), ('AHAFO', 'Ahafo'), ('SAVANNAH', 'Savannah'), ('NORTH_EAST', 'North East'), ('OTI', 'Oti'), ('WESTERN_NORTH', 'Western North')], max_length=20, null=True),
        ),
    ]
